#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'checkMagazine' function below.
#
# The function accepts following parameters:
#  1. STRING_ARRAY magazine
#  2. STRING_ARRAY note
#

def checkMagazine(magazine, note):
    if m < n:
        print("No")
        return
    else:
        magazine_values = {}
        for word in magazine:
            if word in magazine_values:
                magazine_values[word] += 1
            else:
                magazine_values[word] = 1
                
        for word in note:
            if word in magazine_values:
                magazine_values[word] -= 1
            else:
                magazine_values[word] = -1
                
        if min(magazine_values.values()) < 0:
            print("No")
            return
    
    print("Yes")
            

if __name__ == '__main__':
    first_multiple_input = input().rstrip().split()

    m = int(first_multiple_input[0])

    n = int(first_multiple_input[1])

    magazine = input().rstrip().split()

    note = input().rstrip().split()

    checkMagazine(magazine, note)
