/*
Enter your query here.
*/
SELECT CONCAT(OCCUPATIONS.NAME, '(', LEFT(OCCUPATIONS.OCCUPATION, 1), ')') AS RESULT1 
FROM OCCUPATIONS 
ORDER BY OCCUPATIONS.NAME, OCCUPATIONS.OCCUPATION;

SELECT CONCAT('There are a total of ', COUNT(OCCUPATIONS.OCCUPATION), ' ', LOWER(OCCUPATIONS.OCCUPATION), 's.') AS RESULT2 
FROM OCCUPATIONS 
GROUP BY OCCUPATIONS.OCCUPATION
ORDER BY COUNT(OCCUPATIONS.OCCUPATION) ASC, OCCUPATIONS.OCCUPATION ASC;
